"""Canonical products, units, and acquisition costs."""

MARKUP_RATE = 0.25

paper_supplies = [
    {'item_name': 'A4 paper',
     'category': 'paper',
     'unit_price': 0.05,
     'unit': 'sheet'},
    {'item_name': 'Letter-sized paper',
     'category': 'paper',
     'unit_price': 0.06,
     'unit': 'sheet'},
    {'item_name': 'Cardstock',
     'category': 'paper',
     'unit_price': 0.15,
     'unit': 'sheet'},
    {'item_name': 'Colored paper',
     'category': 'paper',
     'unit_price': 0.1,
     'unit': 'sheet'},
    {'item_name': 'Glossy paper',
     'category': 'paper',
     'unit_price': 0.2,
     'unit': 'sheet'},
    {'item_name': 'Matte paper',
     'category': 'paper',
     'unit_price': 0.18,
     'unit': 'sheet'},
    {'item_name': 'Recycled paper',
     'category': 'paper',
     'unit_price': 0.08,
     'unit': 'sheet'},
    {'item_name': 'Eco-friendly paper',
     'category': 'paper',
     'unit_price': 0.12,
     'unit': 'sheet'},
    {'item_name': 'Poster paper',
     'category': 'paper',
     'unit_price': 0.25,
     'unit': 'sheet'},
    {'item_name': 'Banner paper',
     'category': 'paper',
     'unit_price': 0.3,
     'unit': 'sheet'},
    {'item_name': 'Kraft paper',
     'category': 'paper',
     'unit_price': 0.1,
     'unit': 'sheet'},
    {'item_name': 'Construction paper',
     'category': 'paper',
     'unit_price': 0.07,
     'unit': 'sheet'},
    {'item_name': 'Wrapping paper',
     'category': 'paper',
     'unit_price': 0.15,
     'unit': 'sheet'},
    {'item_name': 'Glitter paper',
     'category': 'paper',
     'unit_price': 0.22,
     'unit': 'sheet'},
    {'item_name': 'Decorative paper',
     'category': 'paper',
     'unit_price': 0.18,
     'unit': 'sheet'},
    {'item_name': 'Letterhead paper',
     'category': 'paper',
     'unit_price': 0.12,
     'unit': 'sheet'},
    {'item_name': 'Legal-size paper',
     'category': 'paper',
     'unit_price': 0.08,
     'unit': 'sheet'},
    {'item_name': 'Crepe paper',
     'category': 'paper',
     'unit_price': 0.05,
     'unit': 'sheet'},
    {'item_name': 'Photo paper',
     'category': 'paper',
     'unit_price': 0.25,
     'unit': 'sheet'},
    {'item_name': 'Uncoated paper',
     'category': 'paper',
     'unit_price': 0.06,
     'unit': 'sheet'},
    {'item_name': 'Butcher paper',
     'category': 'paper',
     'unit_price': 0.1,
     'unit': 'sheet'},
    {'item_name': 'Heavyweight paper',
     'category': 'paper',
     'unit_price': 0.2,
     'unit': 'sheet'},
    {'item_name': 'Standard copy paper',
     'category': 'paper',
     'unit_price': 0.04,
     'unit': 'sheet'},
    {'item_name': 'Bright-colored paper',
     'category': 'paper',
     'unit_price': 0.12,
     'unit': 'sheet'},
    {'item_name': 'Patterned paper',
     'category': 'paper',
     'unit_price': 0.15,
     'unit': 'sheet'},
    {'item_name': 'Paper plates',
     'category': 'product',
     'unit_price': 0.1,
     'unit': 'plate'},
    {'item_name': 'Paper cups',
     'category': 'product',
     'unit_price': 0.08,
     'unit': 'cup'},
    {'item_name': 'Paper napkins',
     'category': 'product',
     'unit_price': 0.02,
     'unit': 'napkin'},
    {'item_name': 'Disposable cups',
     'category': 'product',
     'unit_price': 0.1,
     'unit': 'cup'},
    {'item_name': 'Table covers',
     'category': 'product',
     'unit_price': 1.5,
     'unit': 'cover'},
    {'item_name': 'Envelopes',
     'category': 'product',
     'unit_price': 0.05,
     'unit': 'envelope'},
    {'item_name': 'Sticky notes',
     'category': 'product',
     'unit_price': 0.03,
     'unit': 'sheet'},
    {'item_name': 'Notepads',
     'category': 'product',
     'unit_price': 2.0,
     'unit': 'pad'},
    {'item_name': 'Invitation cards',
     'category': 'product',
     'unit_price': 0.5,
     'unit': 'card'},
    {'item_name': 'Flyers',
     'category': 'product',
     'unit_price': 0.15,
     'unit': 'flyer'},
    {'item_name': 'Party streamers',
     'category': 'product',
     'unit_price': 0.05,
     'unit': 'roll'},
    {'item_name': 'Decorative adhesive tape (washi tape)',
     'category': 'product',
     'unit_price': 0.2,
     'unit': 'roll'},
    {'item_name': 'Paper party bags',
     'category': 'product',
     'unit_price': 0.25,
     'unit': 'bag'},
    {'item_name': 'Name tags with lanyards',
     'category': 'product',
     'unit_price': 0.75,
     'unit': 'tag'},
    {'item_name': 'Presentation folders',
     'category': 'product',
     'unit_price': 0.5,
     'unit': 'folder'},
    {'item_name': 'Large poster paper (24x36 inches)',
     'category': 'large_format',
     'unit_price': 1.0,
     'unit': 'sheet'},
    {'item_name': 'Rolls of banner paper (36-inch width)',
     'category': 'large_format',
     'unit_price': 2.5,
     'unit': 'roll'},
    {'item_name': '100 lb cover stock',
     'category': 'specialty',
     'unit_price': 0.5,
     'unit': None},
    {'item_name': '80 lb text paper',
     'category': 'specialty',
     'unit_price': 0.4,
     'unit': None},
    {'item_name': '250 gsm cardstock',
     'category': 'specialty',
     'unit_price': 0.3,
     'unit': None},
    {'item_name': '220 gsm poster paper',
     'category': 'specialty',
     'unit_price': 0.35,
     'unit': None},
]
